add_lunch_combo aokp_d2lte-userdebug
add_lunch_combo aokp_hammerhead-userdebug
add_lunch_combo aokp_jflte-userdebug
add_lunch_combo aokp_mako-userdebug
add_lunch_combo aokp_manta-userdebug
add_lunch_combo aokp_m8-userdebug
